[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
license = "LGPL"
name = "hdfidx"
version = "0.1.0"

[dependencies]
anyhow = "*"
hdf5 = { git = "https://github.com/aldanor/hdf5-rust" }

