[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
keywords = ["hdf"]
license = "LGPL"
name = "hidefix"
version = "0.1.0"
repository = "https://github.com/gauteh/dars"

[dependencies]
anyhow = "1.0.26"
byte-slice-cast = "0.3.5"
byteorder = "1.3.2"

[dependencies.hdf5]
git = "https://github.com/gauteh/hdf5-rust"
branch = "hidefix"

[dependencies.hdf5-sys]
git = "https://github.com/gauteh/hdf5-rust"
features = [ 'static' ]
branch = "hidefix"

