[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
keywords = ["hdf"]
license = "LGPL"
name = "hidefix"
repository = "https://github.com/gauteh/dars"
version = "0.1.0"
[dependencies]
anyhow = "1.0.26"
byte-slice-cast = "0.3.5"
byteorder = "1.3.2"
rio = { version = "0.9", optional = true }

[dependencies.hdf5]
branch = "hidefix"
git = "https://github.com/gauteh/hdf5-rust"

[dependencies.hdf5-sys]
branch = "hidefix"
features = ["static"]
git = "https://github.com/gauteh/hdf5-rust"

[features]
io_uring = [ "rio" ]
