version: '3'

services:
  redis:
    image: redis

  dars:
    build: ../..
    volumes:
      - ../../data:/data:ro


  bloom:
    image: valeriansaliou/bloom:v1.28.0
    depends_on:
      - redis
      - dars
    volumes:
      - ./bloom-config.cfg:/etc/bloom.cfg:ro

  nginx:
    image: nginx
    depends_on:
      - bloom
    ports:
      - 8001:80
    volumes:
      - ./nginx:/etc/nginx:ro


